version: "3"

services:
  registry:
    image: registry:2
    volumes:
      - ./registry/config.yml:/etc/docker/registry/config.yml:ro
#    ports:
#      - "5000:5000"
    container_name: registry
    restart: always
    
  grafana:
    image: grafana/grafana
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
    ports:
      - "3000:3000"
    depends_on:
      - prometheus
    container_name: grafana
    restart: always

  prometheus:
    image: prom/prometheus
    volumes:
      - ./prometheus:/etc/prometheus
#    ports:
#      - "9090:9090"
    container_name: prometheus
    restart: always

  nginx:
    image: nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/logs:/var/log/nginx
    container_name: nginx-webserver
    restart: always


  nginx-fluentd:
    build:
      context: ./fluentd
      dockerfile: Dockerfile
    volumes:
      - ./fluentd:/fluentd/etc
      - ./nginx/logs:/var/log/nginx
#    ports:
#      - "24231:24231"
    container_name: nginx-logExporter
    restart: always

  registry-exporter:
    build:
      context: ./registry-exporter
      dockerfile: Dockerfile
    container_name: registry-exporter
#    ports:
#      - "9055:9055"
    restart: always

  nginx-exporter:
    image: nginx/nginx-prometheus-exporter
    container_name: nginx-exporter
#    ports:
#      - "9113:9113"
    command:
      - -nginx.scrape-uri
      - http://nginx/nginx_status

    depends_on:
      - nginx
    restart: always