global:
  scrape_interval:     15s # Set the scrape interval to every 15 seconds.
  evaluation_interval: 15s # Evaluate rules every 15 seconds.

scrape_configs:

  - job_name: "nginx-exporter"
    static_configs:
      - targets: ["nginx-exporter:9113"]

  - job_name: "nginx-fluentd"
    static_configs:
      - targets: ["nginx-fluentd:24231"]

  - job_name: "registry-exporter"
    static_configs:
      - targets: ["registry-exporter:9055"]
